version: 0.2

env: 
  variables:
    version: "1.0-SNAPSHOT" #pass this to the maven command and dinamically change project version 
phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - whoami
      - java -version
      - mvn --version
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region REGION | docker login --username AWS --password-stdin ACCT_NUMBER.dkr.ecr.REGION.amazonaws.com
      - set REPOSITORY_URI=ACCT_NUMBER.dkr.ecr.REGION.amazonaws.com/APPLICATION
      - set IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
      - echo Building the Docker image...       
      - echo ACCT_NUMBER.dkr.ecr.REGION.amazonaws.com/APPLICATION:latest 
      - cd target  
      - docker build -t ACCT_NUMBER.dkr.ecr.REGION.amazonaws.com/APPLICATION:latest .
      - docker tag ACCT_NUMBER.dkr.ecr.REGION.amazonaws.com/APPLICATION:latest ACCT_NUMBER.dkr.ecr.REGION.amazonaws.com/APPLICATION:$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push ACCT_NUMBER.dkr.ecr.REGION.amazonaws.com/APPLICATION:latest
      - docker push ACCT_NUMBER.dkr.ecr.REGION.amazonaws.com/APPLICATION:$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo Writing image definitions file...
      - export REPOSITORY_URI=ACCT_NUMBER.dkr.ecr.REGION.amazonaws.com/APPLICATION
      - printf '{"ImageURI":"%s"}' "ACCT_NUMBER.dkr.ecr.REGION.amazonaws.com/APPLICATION:$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)" > imageDetail.json
      - cat imageDetail.json  
      - printf '[{"name":"APPLICATION","imageUri":"%s"}]' "ACCT_NUMBER.dkr.ecr.REGION.amazonaws.com/APPLICATION:$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)" > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - appspec.yaml
    - imageDetail.json
    - imagedefinitions.json
  discard-paths: yes
  cache:
   paths:
    - '/root/.m2/**/*'